Tasks/Models/FlowerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Tasks.Models
{
    public class FlowerViewModel
    {
        [Required(ErrorMessage = "Select the flower to display the label")]
        public string SelectedFlower { get; set; }
        public IEnumerable<string> Flowers => new[]
        {
            "Sunflower",
            "Flower 2",
            "Flower 3"
        };
    }
}

Tasks/Controllers/FlowerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tasks.Models;

namespace Tasks.Controllers
{
    public class FlowerController : Controller
    {
        // GET: Flower
        public ActionResult Index()
        {
            ViewBag.Task = "Task 21 - RadioList";
            FlowerViewModel fvm = new FlowerViewModel();
            return View(fvm);
        }

        [HttpPost]
        public ActionResult Index(FlowerViewModel fvm)
        {
            ViewBag.Task = "Task 21 - RadioList";
            return View(fvm);
        }
    }
}

Tasks/Views/Flower/Index.cshtml
@model Tasks.Models.FlowerViewModel

@using (Html.BeginForm("Index", "Flower", FormMethod.Post))
{
    <div class="row">
        <div class="col-6">
            <div class="row">
                @foreach (var flower in Model.Flowers)
                {
                    <div class="col-6">
                        <div class="form-check">
                            @Html.RadioButtonFor(model => model.SelectedFlower, flower, new { @class = "form-check-input" })
                            <label class="form-check-label" for="flexRadioDefault1">
                                @flower
                            </label>
                        </div>
                    </div>
                }
            </div>
            @Html.ValidationMessageFor(model => model.SelectedFlower)
        </div>
    </div>
    <div class="row">
        <div class="text-center">
            <button class="btn btn-primary text" id="submit" type="submit">
                Display Flower Label
            </button>
        </div>
    </div>
}

<div class="row mx-3">
    @Html.DisplayFor(model => model.SelectedFlower)
</div>