Tasks/Models/DigitViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Tasks.Models
{
    public class DigitViewModel
    {
        [Required]
        [Display(Description ="Please enter a 9 digit number")]
        [RegularExpression(@"^[0-9]{9}$", ErrorMessage = "Please enter 9 digit number")]
        public long Number { get; set; }

        [Display(Description = "Unique Digits in the entered number are below")]
        public string UniqueDigits { get; set; }
    }
}

Tasks/Controllers/DigitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tasks.Models;

namespace Tasks.Controllers
{
    public class DigitsController : Controller
    {
        // GET: Digits
        public ActionResult Index()
        {
            ViewBag.Task = "Task 22 - Find Unique Digits in 9 digit number";
            return View();
        }

        [HttpPost]
        public ActionResult Index(DigitViewModel dvm)
        {
            ViewBag.Task = "Task 22 - Find Unique Digits in 9 digit number";
            var list = dvm.Number.ToString().Select(c => int.Parse(c.ToString())).ToList();
            List<int> myList = list.Distinct().ToList();
            dvm.UniqueDigits = string.Join("", myList);
            return View(dvm);
        }
    }
}

Tasks/Views/Digits/Index.cshtml
@model Tasks.Models.DigitViewModel

@using (Html.BeginForm("Index", "Digits", FormMethod.Post, new { @class = "mr-2" }))
{
    <div class="form-row">
        <div class="col-6 mx-2">
            <div class="form-group">
                @Html.LabelFor(model => model.Number, new { @class = "form-label" })
                @Html.TextBoxFor(model => model.Number, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Number)
            </div>
        </div>
        <div class="row mt-3">
            <div class="text-center">
                <button type="submit" class="btn btn-primary text ">
                    FInd Unique Digits
                </button>
            </div>
        </div>
    </div>
}



<form>
    <div class="form-group">
        <label>Unique Digits in entered number are : </label>
        @Html.DisplayFor(model => model.UniqueDigits)
    </div>
</form>